/******************************************************************************
 *
 * Module: PORT
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - PORT Driver
 *
 * Author: Bassam Ashraf
 ******************************************************************************/

#include "Port_PBcfg.h"

/* Array of structure that hold configurations of ports each structure include:
 * 1. The port ID number.
 * 2. The pin number.
 * 3. Initial mode --> DIO or CAN or ADC or ....
 * 4. Direction of pin --> INPUT or OUTPUT.
 * 5. Internal resistor --> Disable, Pull up or Pull down.
 * 6. Initial level value for pin --> Low or High.
 * 7. EN/DIS Digital mode for this pin.
 * 8. EN/DIS direction changeable during runtime.
 * 9. EN/DIS mode changeable during runtime. */

const Port_ConfigType Port_PinsConfigurations [NUMBER_OF_PORT_PINS] =
{
     /* Default configurations DIO mode for all ports */
     { PORT_A_ID, PORT_A_PIN_0, PORT_A0_MODE_UART0_RX, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, FALSE, TRUE },   /* PA0 (UART0 RX) */
     { PORT_A_ID, PORT_A_PIN_1, PORT_A1_MODE_UART0_TX, PORT_PIN_OUT, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, FALSE, TRUE },  /* PA1 (UART0 TX) */
     { PORT_A_ID, PORT_A_PIN_2, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PA2 (GPIO) */
     { PORT_A_ID, PORT_A_PIN_3, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PA3 (GPIO) */
     { PORT_A_ID, PORT_A_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PA4 (GPIO) */
     { PORT_A_ID, PORT_A_PIN_5, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PA5 (GPIO) */
     { PORT_A_ID, PORT_A_PIN_6, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PA6 (GPIO) */
     { PORT_A_ID, PORT_A_PIN_7, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PA7 (GPIO) */


     { PORT_B_ID, PORT_B_PIN_0, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PB0 (GPIO) */
     { PORT_B_ID, PORT_B_PIN_1, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PB1 (GPIO) */
     { PORT_B_ID, PORT_B_PIN_2, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PB2 (GPIO) */
     { PORT_B_ID, PORT_B_PIN_3, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PB3 (GPIO) */
     { PORT_B_ID, PORT_B_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PB4 (GPIO) */
     { PORT_B_ID, PORT_B_PIN_5, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PB5 (GPIO) */
     { PORT_B_ID, PORT_B_PIN_6, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PB6 (GPIO) */
     { PORT_B_ID, PORT_B_PIN_7, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PB7 (GPIO) */


     { PORT_C_ID, PORT_C_PIN_0, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PC0 (JTAG TCK) */
     { PORT_C_ID, PORT_C_PIN_1, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PC1 (JTAG TMS) */
     { PORT_C_ID, PORT_C_PIN_2, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PC2 (JTAG TDI) */
     { PORT_C_ID, PORT_C_PIN_3, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PC3 (JTAG TDO) */
     { PORT_C_ID, PORT_C_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PC4 (GPIO) */
     { PORT_C_ID, PORT_C_PIN_5, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PC5 (GPIO) */
     { PORT_C_ID, PORT_C_PIN_6, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PC6 (GPIO) */
     { PORT_C_ID, PORT_C_PIN_7, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PC7 (GPIO) */


     { PORT_D_ID, PORT_D_PIN_0, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PD0 (GPIO) */
     { PORT_D_ID, PORT_D_PIN_1, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PD1 (GPIO) */
     { PORT_D_ID, PORT_D_PIN_2, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PD2 (GPIO) */
     { PORT_D_ID, PORT_D_PIN_3, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PD3 (GPIO) */
     { PORT_D_ID, PORT_D_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PD4 (GPIO) */
     { PORT_D_ID, PORT_D_PIN_5, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PD5 (GPIO) */
     { PORT_D_ID, PORT_D_PIN_6, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PD6 (GPIO) */
     { PORT_D_ID, PORT_D_PIN_7, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PD7 (GPIO, locked by default) */


     { PORT_E_ID, PORT_E_PIN_0, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PE0 (GPIO) */
     { PORT_E_ID, PORT_E_PIN_1, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PE1 (GPIO) */
     { PORT_E_ID, PORT_E_PIN_2, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PE2 (GPIO) */
     { PORT_E_ID, PORT_E_PIN_3, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PE3 (GPIO) */
     { PORT_E_ID, PORT_E_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PE4 (GPIO) */
     { PORT_E_ID, PORT_E_PIN_5, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PE5 (GPIO) */


     { PORT_F_ID, PORT_F_PIN_0, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PF0 (GPIO, locked by default) */
     { PORT_F_ID, PORT_F_PIN_1, PORT_PIN_MODE_DIO, PORT_PIN_OUT, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },   /* PF1 (GPIO) LED_RED */
     { PORT_F_ID, PORT_F_PIN_2, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PF2 (GPIO) */
     { PORT_F_ID, PORT_F_PIN_3, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_OFF, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE },    /* PF3 (GPIO) */
     { PORT_F_ID, PORT_F_PIN_4, PORT_PIN_MODE_DIO, PORT_PIN_IN, INTERNAL_RESISTOR_PULL_UP, PORT_PIN_LEVEL_LOW, TRUE, TRUE, TRUE } /* PF4 (GPIO) SW1 */

};
